/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_aix_perfstat */

#ifndef _Included_com_ibm_aix_perfstat
#define _Included_com_ibm_aix_perfstat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_aix_perfstat
 * Method:    print
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_aix_perfstat_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
